import React, { useEffect, useState } from 'react'
import Loader from './Loader'
import Card from './Card'
import FormField from './FormField';
import axios from 'axios';


const RenderCards=({data,title})=>{
    return  data?.length>0?(
        data.map((post)=>(
              <Card key={post._id} {...post} />
         ))
    ):(
        (<h1 className='font-bold mt-5 text-[#6964ff] text-xl '>{title}</h1>)
     )

}
function Home() {
    
    const [loading,setLoading]=useState(false);
    const [allPosts,setAllPost]=useState(null);
    const [searchResult,setSearchResult]=useState('');
    const [searchResponse,setSearchResponse]=useState(null)
    const [searchTimeOut,setSearchTimeOut]=useState(null)

    useEffect(()=>{
        const fetchPost=async()=>{
            setLoading(true);
            axios.get("http://localhost:3000/api/v1/post",{
                headers:{
                    "Content-Type":"application/json"
                }
            }).then(res=>{
                console.log(res.data.data.reverse());
                setAllPost(res.data.data.reverse());
                console.log(allPosts)
                setLoading(false);
            }).catch(err=>{
                console.log(err);
                alert(err.message);
                setLoading(false);
            })
        }
        fetchPost();
    },[])
    const handleSearchResult=(e)=>{
        clearTimeout(searchTimeOut)
        setSearchResult(e.target.value)
      setSearchTimeOut(
        setTimeout(()=>{
            const searchImage=allPosts.filter((item)=>item.name.toLowerCase().includes(searchResult.toLowerCase()) || item.prompt.toLowerCase().includes(searchResult.toLowerCase()))

            setSearchResponse(searchImage)
        },500)

      )
    }

     
  return (
    <div className='max-w-7xl mx-auto'>
        {/* top heading */}
        <div>
            <h1 className='text-xl  font-extrabold text-[#222328]'>The Community Showcase</h1>
            <p className='text-[#666e75] font-normal text-lg max-w-[500px]'>Browse through a collection of imaginative and visually stunning images generated by DALL-E AI</p>
        </div>
        {/* formfield */}
        <div className='mt-16'>
        <FormField 
        LabelName="Search posts"
        type="text"
        name="response"
        placeholder="search images"
        value={searchResult}
        handleChange={handleSearchResult} />
        </div>
        {/* card */}
        <div className='mt-10'>
            {
                loading?(
                    <div className='flex justify-center items-center'>
                    <Loader />
                    </div>
                ):(
                    <>
                        {
                            searchResult && (
                                <h2 className='mb-3 text-xl font-medium text-[#666e75]'>
                                    showing search result for <span className='text-[#6964ff]'>{searchResult}</span>
                                </h2>
                            )
                        }
                        <div className='grid lg:grid-cols-4 sm:grid-cos-3 xs:grid-cols-2 grid-cols-1 gap-3 '>
                            {
                                searchResult?(
                                    <RenderCards data={searchResponse} title="No Post for Searched Result" />
                                ):(
                                    <RenderCards data={allPosts} title="No Post Found" />
                                )
                            }

                        </div>
                    </>
                )
            }
        </div>
      
    </div>
  )
}

export default Home
